import * as Yup from "yup";

export const initialValues = {
  fullName: "",
  fatherName: "",
  rollNo: "",
  dob: "",
  gender: "",
  cnic: "",
  photo: null,
  class: "",
  class_fees: "",
  section: "",
  prevSchool: "",
  lastResult: "",
  admissionDate: "",
  mobile: "",
  altContact: "",
  email: "",
  city: "",
  address: "",
  fatherFullName: "",
  fatherCNIC: "",
  occupation: "",
  fatherPhone: "",
  motherName: "",
  motherPhone: "",
  blood: "",
  emergency: "",
  medical: "",
  disability: "",
  transport: false,
  busRoute: "",
  hostel: false,
  studentPhoto: null,
  bFormCopy: null,
  prevResultCard: null,
  guardianCnic: null,
};

export const validationSchema = Yup.object().shape({
  fullName: Yup.string().required("Full name is required"),
  fatherName: Yup.string().required("Father's name is required"),
  dob: Yup.string().required("Date of birth is required"),
  gender: Yup.string().required("Gender is required"),
  class: Yup.string().required("Admission class is required"),
  class_fees: Yup.number().typeError("Must be a number").min(0, "Cannot be negative").nullable(),
  section: Yup.string().required("Section is required"),
  mobile: Yup.string().required("Mobile number is required"),
  email: Yup.string().email("Invalid email address").nullable(),
});
